// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: reply/reply.proto

package reply

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OnlineMessageRelayService_OnlinePushMsg_FullMethodName = "/pbReply.OnlineMessageRelayService/OnlinePushMsg"
)

// OnlineMessageRelayServiceClient is the client API for OnlineMessageRelayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OnlineMessageRelayServiceClient interface {
	OnlinePushMsg(ctx context.Context, in *OnlinePushMsgReq, opts ...grpc.CallOption) (*OnlinePushMsgResp, error)
}

type onlineMessageRelayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnlineMessageRelayServiceClient(cc grpc.ClientConnInterface) OnlineMessageRelayServiceClient {
	return &onlineMessageRelayServiceClient{cc}
}

func (c *onlineMessageRelayServiceClient) OnlinePushMsg(ctx context.Context, in *OnlinePushMsgReq, opts ...grpc.CallOption) (*OnlinePushMsgResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnlinePushMsgResp)
	err := c.cc.Invoke(ctx, OnlineMessageRelayService_OnlinePushMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnlineMessageRelayServiceServer is the server API for OnlineMessageRelayService service.
// All implementations must embed UnimplementedOnlineMessageRelayServiceServer
// for forward compatibility.
type OnlineMessageRelayServiceServer interface {
	OnlinePushMsg(context.Context, *OnlinePushMsgReq) (*OnlinePushMsgResp, error)
	mustEmbedUnimplementedOnlineMessageRelayServiceServer()
}

// UnimplementedOnlineMessageRelayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnlineMessageRelayServiceServer struct{}

func (UnimplementedOnlineMessageRelayServiceServer) OnlinePushMsg(context.Context, *OnlinePushMsgReq) (*OnlinePushMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnlinePushMsg not implemented")
}
func (UnimplementedOnlineMessageRelayServiceServer) mustEmbedUnimplementedOnlineMessageRelayServiceServer() {
}
func (UnimplementedOnlineMessageRelayServiceServer) testEmbeddedByValue() {}

// UnsafeOnlineMessageRelayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnlineMessageRelayServiceServer will
// result in compilation errors.
type UnsafeOnlineMessageRelayServiceServer interface {
	mustEmbedUnimplementedOnlineMessageRelayServiceServer()
}

func RegisterOnlineMessageRelayServiceServer(s grpc.ServiceRegistrar, srv OnlineMessageRelayServiceServer) {
	// If the following call pancis, it indicates UnimplementedOnlineMessageRelayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OnlineMessageRelayService_ServiceDesc, srv)
}

func _OnlineMessageRelayService_OnlinePushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlinePushMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineMessageRelayServiceServer).OnlinePushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnlineMessageRelayService_OnlinePushMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineMessageRelayServiceServer).OnlinePushMsg(ctx, req.(*OnlinePushMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OnlineMessageRelayService_ServiceDesc is the grpc.ServiceDesc for OnlineMessageRelayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnlineMessageRelayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbReply.OnlineMessageRelayService",
	HandlerType: (*OnlineMessageRelayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnlinePushMsg",
			Handler:    _OnlineMessageRelayService_OnlinePushMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reply/reply.proto",
}
