admin:
  emails : [ 1366502108@qq.com ]

mysql:
  dbMysqlAddress: [ 127.0.0.1:13306 ]
  dbMysqlUserName: root
  dbMysqlPassword: qin1002.
  dbMysqlDatabaseName: studyim

log:
  storageLocation: ./logs/
  rotationTime: 24
  remainRotationCount: 5
  remainLogLevel: 6
