#--------------- Internal service configuration ---------------#
serverip: 0.0.0.0

api:
  apiPort: [ 10000 ]

rpcport:
  accountPort: [ 10100 ]
  friendPort: [ 10200 ]
  offlineMessagePort: [ 10300 ]
  groupPort: [ 10500 ]

rpcregistername:
  accountName: Account
  friendName: Friend
  offlineMessageName: OfflineMessage
  groupName: Group

admin:
  userIds : [ ]

tokenpolicy:
  secret: study-im-server
  accessExpire: 1

log:
  storageLocation: ../logs/
  rotationTime: 24
  remainRotationCount: 5
  remainLogLevel: 6

longconnsvr:
  wsPort: [ 17778 ]
  websocketMaxConnNum: 10000
  websocketMaxMsgLen: 4096
  websocketTimeout: 1000

#--------------- Infrastructure configuration ---------------#
zookeeper:
  zkSchema: studyIM
  zkAddr: [ 127.0.0.1:12181 ]

mysql:
  dbMysqlAddress: [ 127.0.0.1:13306 ]
  dbMysqlUserName: root
  dbMysqlPassword: qin1002.
  dbMysqlDatabaseName: studyim

redis:
  dbAddress: 127.0.0.1:16379
  dbPassword: qin1002. 

kafka:
  ws2mschat:
    addr: [ 127.0.0.1:9092 ]
    topic: "ws2ms_chat"
  ms2pschat:
    addr: [ 127.0.0.1:9092 ]
    topic: "ms2ps_chat"
  consumergroupid:
    msgToMongo: mongo
    msgToMySql: mysql
    msgToPush: push
