#--------------- Internal service configuration ---------------#
serverip: 0.0.0.0

api:
  apiPort: [ 10000 ]

rpcport:
  accountPort: [ 10100 ]
  friendPort: [ 10200 ]
  offlineMessagePort: [ 10300 ]
  onlineMessageRelayPort: [ 10400 ]
  groupPort: [ 10500 ]
  pushPort: [ 10700 ]
  conversationPort: [ 11100 ]

rpcregistername:
  accountName: Account
  friendName: Friend
  offlineMessageName: OfflineMessage
  onlineMessageRelayName: OnlineMessageRelay
  groupName: Group
  pushName: Push
  conversationName: Conversation

admin:
  userIds : [ ]

tokenpolicy:
  secret: study-im-server
  accessExpire: 1

log:
  storageLocation: ../logs/
  rotationTime: 24
  remainRotationCount: 5
  remainLogLevel: 6

longconnsvr:
  wsPort: [ 17778 ]
  websocketMaxConnNum: 10000
  websocketMaxMsgLen: 4096
  websocketTimeout: 1000

#--------------- Infrastructure configuration ---------------#
etcd:
  etcdSchema: studyim
  etcdAddr: [ 127.0.0.1:12379 ]

mysql:
  dbMysqlAddress: [ 127.0.0.1:13306 ]
  dbMysqlUserName: root
  dbMysqlPassword: qin1002.
  dbMysqlDatabaseName: studyim

mongo:
  dbAddress: [ 127.0.0.1:37017 ]
  dbMongoUserName: root
  dbMongoPassword: qin1002.
  dbDirect: false
  dbTimeout: 10
  dbDatabase: studyIM
  dbSource: admin
  dbMaxPoolSize: 20
  dbRetainChatRecords: 14

redis:
  dbAddress: 127.0.0.1:16379
  dbPassword: qin1002. 

kafka:
  ws2mschat:
    addr: [ 127.0.0.1:19094 ]
    topic: "offlineMsgToMongoMysql"
  ms2pschat:
    addr: [ 127.0.0.1:19094 ]
    topic: "msgToPush"
  consumergroupid:
    msgToMongo: mongo
    msgToMySql: mysql
    msgToPush: push
